### ISSUE TITLE
Waiting 30s error in trakt

### ISSUE THREAD

**Issue by aicynide** [po5/player-tracker#6]

**Comment by aicynide** [comment]
@po5 hello friend you script is really very helpful please fix this error

**Comment by po5** [comment]
Hello most esteemed friend,
It appears your issue is that you either didn't follow the installation instructions or don't understand the regular operation of this program.
It is supposed to wait 30 seconds https://github.com/po5/player-tracker/blob/master/player-tracker.py#L187-L188
How you think there's any error with Trakt is beyond me.
Reopen with an actual bug report and I'll take a look.
